version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - run:
          name: install packages
          command: npm install
      - run:
          name: Run Tests
          command: npm run test
      - setup_remote_docker
      - run:
          command: |
            docker build -t dehanz13/pos:latest .
            echo "52604aa2-d72d-487d-9658-cfc80feb0040" | docker login -u "dehanz13" --password-stdin
            docker push dehanz13/pos:latest

workflows:
  version: 2
  build-master:
    jobs:
      - test
